### ISSUE TITLE
how to resolve this error in vs code?

### ISSUE THREAD

**Issue by sheebhaAustin** [microsoft/vscode-js-debug#1172]
Debugger listening on ws://127.0.0.1:64272/7a75b7af-1519-440c-8289-c1919b41d4ad
For help, see: https://nodejs.org/en/docs/inspector
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn (child_process.js:551:9)
    at bootloader.bundle.cdp:2:85526
    at bootloader.bundle.cdp:2:86504
    at Object.7207 (bootloader.bundle.cdp:2:86704)
    at __webpack_require__ (bootloader.bundle.cdp:2:92949)
    at bootloader.bundle.cdp:2:93102
    at Object.<anonymous> (bootloader.bundle.cdp:2:93129)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

**Comment by connor4312** [comment]
Can you please share more repro steps / information about how you encountered this error?
