### ISSUE TITLE
spawn UNKNOWN

### ISSUE THREAD

**Issue by Lustellz** [microsoft/vscode-js-debug#1173]
Hello, I had encountered a continuous and unknown error log. According to your guidance provided in the log, I'm writing the Issue.
It occurs whenever I perform npm command.

Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at spawn (child_process.js:677:9)
    at Object.spawnWithSignal [as spawn] (child_process.js:911:17)
    at bootloader.bundle.cdp:2:85526
    at bootloader.bundle.cdp:2:86504
    at Object.7207 (bootloader.bundle.cdp:2:86704)
    at __webpack_require__ (bootloader.bundle.cdp:2:92949)
    at bootloader.bundle.cdp:2:93102
    at Object.<anonymous> (bootloader.bundle.cdp:2:93129)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
up to date in 0.029s

**Comment by connor4312** [comment]
Can you provide some more info about the environment you're running in? Such as, which OS, how Node is installed, etc.

**Comment by Lustellz** [comment]
I use Windows 10 with node version 16.13.2 and npm version 8.1.2.

2022년 2월 1일 (화) 오전 3:36, Connor Peet ***@***.***>님이 작성:

**Comment by SanchayUp** [comment]
I've faced this error while running cmd yarn start 
in my package.json script `"start": "env-cmd -f .env.dev craco start --reset-cache",`

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at spawn (child_process.js:677:9)
    at Object.spawnWithSignal [as spawn] (child_process.js:911:17)
    at Object.spawn (C:\laragon\www\holisticqipadmin\node_modules\cross-spawn\index.js:12:24)
    at Object.EnvCmd (C:\laragon\www\holisticqipadmin\node_modules\env-cmd\dist\env-cmd.js:59:26)
    at async Object.CLI (C:\laragon\www\holisticqipadmin\node_modules\env-cmd\dist\env-cmd.js:19:16) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
  
  Please help me.

**Comment by connor4312** [comment]
That is not related and looks like a problem with your script, not this debugger
