### ISSUE TITLE
debug console not showing output

### ISSUE THREAD

**Issue by DannKey** [microsoft/vscode-js-debug#1200]
Here is the error i receive when i press Ctr+F5 when i try to print an output in the debug. 

Error in the js-debug bootloader, please report to [https://aka.ms/js-dbg-issue](): Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at spawn (child_process.js:667:9)
    at spawnWithSignal (child_process.js:871:17)
    at bootloader.bundle.cdp:2:91277
    at bootloader.bundle.cdp:2:92254
    at Object.7207 (bootloader.bundle.cdp:2:92454)
    at __webpack_require__ (bootloader.bundle.cdp:2:98731)
    at bootloader.bundle.cdp:2:98884
    at Object.<anonymous> (bootloader.bundle.cdp:2:98911)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '[c:\Users\1-PC\Desktop\]()ФУНДАМЕНТАЛС\Fundamentals\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Process exited with code 1

How do i fix this?

**Comment by connor4312** [comment]
```
throw err;
^

Error: Cannot find module '[c:\Users\1-PC\Desktop]()ФУНДАМЕНТАЛС\Fundamentals\index.js'
```

The module you're trying to run cannot be found.

**Comment by DannKey** [comment]
Its a folder i'm using daily , what's the reason for crashing like that all of a sudden ? 
Need more info on how to fix it.
