### ISSUE TITLE
Error activating auto attach running "node index.js"

### ISSUE THREAD

**Issue by NTTAKR** [microsoft/vscode-js-debug#1238]
Hi, 

I have the current nightly build installed and get an error "toast" on the right side "Cannot read properties of undefined (reading 'logger')" after starting node index.js. 

Reading through the log window settings I get this information: 

[2022-04-15 13:35:30.312] [renderer1] [error] Cannot read properties of undefined (reading 'logger'): TypeError: Cannot read properties of undefined (reading 'logger')
    at error (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:9992)
    at us.handleSaveError (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:131411)
    at vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:130816
[2022-04-15 13:38:41.453] [renderer1] [error] issue not found utf-8
[2022-04-15 13:40:15.136] [renderer1] [error] Error: Unable to read file '\\vscode-app\c:\Users\akr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js:610:9992' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\vscode-app\c:\Users\akr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js:610:9992')
    at p.doReadFileStream (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:33842)
    at async doRead (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:110433)
    at async d.readStream (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:110108)
    at async ji.resolveFromFile (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2661:66651)
    at async u.doResolve (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2666:104975)
    at async ya.doResolveAsText (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2132:89317)
    at async g.setInput (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2636:111961)
    at async i.doSetInput (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2636:26823)
    at async i.doOpenEditor (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2636:25196)
    at async i.openEditor (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2636:24822)
    at async vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2842:17260
    at async C.doOpenCodeEditor (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1346:31316)
    at async S.open (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:62491)
    at async s.open (vscode-file://vscode-app/c:/Users/akr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:63952)

What is this stuff? Can I get rid of it? 
When is this installed?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1235
