### ISSUE TITLE
Stack trace from throw in debug console should hide everything below "eval"

### ISSUE THREAD

**Issue by jakebailey** [microsoft/vscode-js-debug#1259]
**Is your feature request related to a problem? Please describe.**

When I do something in the debug console that throws, I get a huge massive error message, which I have to scroll all the way past to figure out what I did wrong (99% of the time, I've hit enter instead of tab when trying to auto-complete; that's a different problem).

**Describe the feature you'd like**

The stack trace that is shown for errors that are thrown should drop anything past the eval, since that's where the executed code is actually rooted from. Nothing below eval in the trace string is really controllable; that's just where you are in the debug session.

Anything `eval` and "above" is what should be kept, so you can see errors thrown from functions called from the console, like:

![image](https://user-images.githubusercontent.com/5341706/167220209-5810ce60-858d-4549-a672-36d9b41d222b.png)

**Comment by jakebailey** [comment]
Just so you can see how huge I'm talking about, this is what I get on a regular basis debugging TS...

<details>
<summary>Details</summary>

```
Uncaught TypeError TypeError: Cannot read property 'pos' of undefined
    at makeAsExpression (e:\work\TypeScript\src\compiler\parser.ts:4884:77)
    at eval (<eval>/VM46952632:1:1)
    at parseSourceFileWorker (e:\work\TypeScript\src\compiler\parser.ts:1118:32)
    at parseSourceFile (e:\work\TypeScript\src\compiler\parser.ts:935:28)
    at createSourceFile (e:\work\TypeScript\src\compiler\parser.ts:720:29)
    at <anonymous> (e:\work\TypeScript\src\harness\fakesHosts.ts:353:31)
    at findSourceFileWorker (e:\work\TypeScript\src\compiler\program.ts:2919:31)
    at findSourceFile (e:\work\TypeScript\src\compiler\program.ts:2812:28)
    at <anonymous> (e:\work\TypeScript\src\compiler\program.ts:2764:29)
    at getSourceFileFromReferenceWorker (e:\work\TypeScript\src\compiler\program.ts:2727:36)
    at processSourceFile (e:\work\TypeScript\src\compiler\program.ts:2762:13)
    at processRootFile (e:\work\TypeScript\src\compiler\program.ts:2541:13)
    at <anonymous> (e:\work\TypeScript\src\compiler\program.ts:1199:49)
    at forEach (e:\work\TypeScript\src\compiler\core.ts:38:32)
    at createProgram (e:\work\TypeScript\src\compiler\program.ts:1199:13)
    at compileFiles (e:\work\TypeScript\src\harness\compilerImpl.ts:261:54)
    at compileFiles (e:\work\TypeScript\src\harness\harnessIO.ts:434:37)
    at CompilerTest (e:\work\TypeScript\src\testRunner\compilerRunner.ts:237:36)
    at <anonymous> (e:\work\TypeScript\src\testRunner\compilerRunner.ts:86:32)
    at callFn (e:\work\TypeScript\node_modules\mocha\lib\runnable.js:366:21)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runnable.js:354:5)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:498:10)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:559:5)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:558:10)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:903:8)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
    --- Immediate ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:199:43)
    at emitInitScript (internal/async_hooks.js:467:3)
    at initAsyncResource (internal/timers.js:157:5)
    at Immediate (timers.js:246:5)
    at setImmediate (timers.js:300:10)
    at next (e:\work\TypeScript\node_modules\mocha\lib\runner.js:880:14)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:849:12)
    at <anonymous> (e:\work\TypeScript\node_modules\mocha\lib\runner.js:881:14)
    at processImmediate (internal/timers.js:461:21)
    at callbackTrampoline (internal/async_hooks.js:131:14)
```

</details>

**Comment by jakebailey** [comment]
I also swear this used to not be the case at all; the huge stack traces are something that I only started seeing recently, so maybe this is a bug and this is supposed to be working as I describe.

**Comment by connor4312** [comment]
Fair suggestion, should not be terribly hard, we [already have a stacktrace parser](https://github.com/microsoft/vscode-js-debug/blob/main/src/common/stackTraceParser.ts). Code pointer:

https://github.com/microsoft/vscode-js-debug/blob/0d435a1c81b53c9e67c85eb5e64d92a418c169f7/src/adapter/threads.ts#L472-L478

**Comment by jakebailey** [comment]
Interesting, thanks for pointing that out. I imagine we'd need to know exactly which `eval` was triggered by the debug console, otherwise it could be cut off at the wrong one.

**Comment by connor4312** [comment]
The code path I linked deals with the response from a REPL evaluation. However, yes, we need to know what frame in the evaluation was the REPL. One way to do this would be to name the sources by appending a `\n//# sourceURL=...` comment at the end prior to evaluation. We [do that](https://github.com/microsoft/vscode-js-debug/blob/1ea758e0b8936b3b6cf5ff55414146574dfae7c7/src/adapter/templates/index.ts#L11-L15) for internal scripts to avoid cluttering the Loaded Scripts view.

**Comment by jakebailey** [comment]
I have it working; will send something on Monday.

![image](https://user-images.githubusercontent.com/5341706/167230761-02128a84-b3d4-4165-ae57-ad0a6b1171ca.png)

**Comment by jakebailey** [comment]
This has been working great, but I did notice that syntax errors aren't caught in the same way; the REPL frame doesn't seem to be in the trace when that happens, confusingly.

**Comment by connor4312** [comment]
It makes a bit of sense: we append `//# sourceURL` to identify REPL scripts, but if the script fails to parse V8 probably aborts and throws before it gets to and assigns that URL.

**Comment by jakebailey** [comment]
Even weirder, in that `eval` is not even in the stack at all:

![image](https://user-images.githubusercontent.com/5341706/176508528-11dfeebb-6ed2-48d8-bc3e-59e06ccf05cb.png)

You can see this if you just try using eval; the best one can do is to wrap the eval in another eval:

![image](https://user-images.githubusercontent.com/5341706/176509006-a1be0181-5365-42ef-913a-82820299f5f5.png)

But, that's not very helpful for traces when there isn't a syntax error. I would really think that these types of errors would include `eval`, but that'd be a V8 thing to change, and wouldn't help the debugging experience if `sourceURL` isn't parsed.

**Comment by jakebailey** [comment]
Why Chrome/Edge's debugger gets an `anonymous:...` and VS Code does not, I have no idea. Maybe that would help.

I can file a bug for syntax errors to not keep talking on a closed issue; I forgot to test syntax errors when I was working on my PR to close this issue.

**Comment by jakebailey** [comment]
@connor4312 Was the fix for this reverted at some point? I back to getting huge backtraces when I make typos.

**Comment by connor4312** [comment]
I've anecdotally seen this, but of course now that I try to reproduce it, am having trouble hitting it. If you hit this again before I do, can you share where you were and the contents of your debug console?

**Comment by jakebailey** [comment]
I also somehow cannot reproduce it. Very confusing. I will keep my eye out and get some sort of backtrace the next time it happens.

**Comment by jakebailey** [comment]
Actually, that is relevant. This only happens when the renaming is wrong. If I type `links1` or even `links2`, the trace is properly truncated.

**Comment by connor4312** [comment]
It's our old friend sourcemap renames: in renaming identifiers, the program is re-generated from its AST, and Acorn is not aware of comments

**Comment by rebornix** [comment]
Confirmed that it's showing long call stacks in VS Code Stable but not in Insiders.
