### ISSUE TITLE
callFrame.url is undefined

### ISSUE THREAD

**Issue by pilaoda** [microsoft/vscode-js-debug#1327]
This error happen when pause on my breakpoint, and the debugger not work at all.

rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'endsWith')
c:\Users\wgx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89
stack trace: TypeError: Cannot read properties of undefined (reading 'endsWith')
    at new StackFrame (d:\ts_projects\vscode-js-debug\src\adapter\stackTrace.ts:274:37)
    at Function.fromDebugger (d:\ts_projects\vscode-js-debug\src\adapter\stackTrace.ts:252:20)
    at Function.fromDebugger (d:\ts_projects\vscode-js-debug\src\adapter\stackTrace.ts:90:68)
    at Thread._createPausedDetails (d:\ts_projects\vscode-js-debug\src\adapter\threads.ts:1152:35)
    at Thread._onPaused (d:\ts_projects\vscode-js-debug\src\adapter\threads.ts:875:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

![image](https://user-images.githubusercontent.com/12658348/178105452-1056f2eb-111e-463b-a9bb-2e389b0bdbae.png)

**Comment by pilaoda** [comment]
This error never happened before the vscode 1.69 version

**Comment by pilaoda** [comment]
BTW, my v8 runtime is 5.8.283.

**Comment by connor4312** [comment]
How can I reproduce this?

**Comment by pilaoda** [comment]
> How can I reproduce this?

Debug with v8 5.8.283 would reproduce this problem，because there is no url in callFrame in 5.9.283.

**Comment by pilaoda** [comment]
I suggest mark the url as optional, and fix all the places use this property. I also notice that it is marked as deprecated, or consider just delete it?

**Comment by connor4312** [comment]
Oh, yea, looks like that usage was introduced in a pull request. I'll add it to my list, PR welcome too--we should just look at the first frame in the stack instead.

**Comment by pilaoda** [comment]
I would like to add a PR, and I have two ideas:
1. mark the url as optional.
2. set a default value "" when url is undefined.
What do you think? 
If idea 2 is chosen, I need some guidance for the place to set default value.

**Comment by pilaoda** [comment]
![image](https://user-images.githubusercontent.com/12658348/178141793-5b398acf-f71b-4f6e-857e-9bc84e794a75.png)
I try to add a PR, but an error occured when I commit to my fork. What should I do?

**Comment by connor4312** [comment]
Edited my previous comment: as mentioned, we should not use `callFrame.url` at all. Instead, we should look up the script from the script container and use its URL like we do here:

https://github.com/microsoft/vscode-js-debug/blob/c4c7620b7cb1a10f69d9dd0e6cdbaa90247eb796/src/adapter/exceptionPauseService.ts#L184

I'm not sure why you're seeing those errors, make sure that you're using an up to date version of TypeScript in your VS Code instance.

**Comment by TylerLeonhardt** [comment]
any verification steps?

**Comment by connor4312** [comment]
@pilaoda does the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) (or just using VS Code Insiders) resolve this issue for you?

**Comment by pilaoda** [comment]
> @pilaoda does the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) (or just using VS Code Insiders) resolve this issue for you?

yes, the nightly build resolve this issue for me. Thanks.
