### ISSUE TITLE
Setting breakpoint fails if certain unicode characters are in the path

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#1364]
**Describe the bug**
Setting breakpoint fails if certain unicode characters (e.g. 😊) are in the path. Stack trace: 
```
Error processing setBreakpoints: URIError: URI malformed
    at encodeURIComponent (<anonymous>)
    at C (c:\Users\aerie\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2022.8.417\src\extension.js:2:1066907)
    at O (c:\Users\aerie\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2022.8.417\src\extension.js:2:1067205)
    at t.urlToRegex (c:\Users\aerie\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2022.8.417\src\extension.js:2:1067515)
    at v.absolutePathToUrlRegexp (c:\Users\aerie\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2022.8.417\src\extension.js:2:1122884)
    at l._setByPath (c:\Users\aerie\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2022.8.417\src\extension.js:2:797650)
    at l.enable (c:\Users\aerie\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2022.8.417\src\extension.js:2:794119)
    at c:\Users\aerie\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2022.8.417\src\extension.js:2:790310
    at Array.map (<anonymous>)
    at D.setBreakpoints (c:\Users\aerie\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2022.8.417\src\extension.js:2:790300)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.default._onMessage (c:\Users\aerie\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2022.8.417\src\extension.js:2:1078258)"
```

**To Reproduce**

Folder structure:
![image](https://user-images.githubusercontent.com/38218905/183527192-15b2fbbe-2e83-4e17-b8a4-a006f86dc81d.png)

index.html:
```
<head>
</head>
<body>
    <h1>yay emojis</h1>
    <script src="😊/test.js"></script>
</body>
```

test.js:
```
console.log('foo');
```

**Log File**
[log.txt](https://github.com/microsoft/vscode-js-debug/files/9285439/log.txt)

**VS Code Version:** 
![image](https://user-images.githubusercontent.com/38218905/183527411-8644dfc5-726e-4460-85fa-79067430d6ba.png)

**Comment by aeschli** [comment]
Verified with JavaScript Debugger (Nightly) v2022.10.1817
