### ISSUE TITLE
Set breakpoint before launch will stuck

### ISSUE THREAD

**Issue by YiFan0221** [microsoft/vscode-js-debug#1608]
Hi,

Once set breakpoint before launch debugger.
When click F5 to launch.
On Run and Debug page of VSCode:
"BREAKPOINTS"       :  this breakpoint show unbound.
"LOADED SCRIPTS"  :  only few files has been loaded. 
(XXX-config.js 、 static/js/bundle.js 、 .../webpack/bootstrap)

But if set breakpoint after launch.
It will be normal.

The steps about this case.
Step 1. yarn start
Step 2. set breakpoint <<<
Step 3. Click "F5" Launch script.
Step 4. Chrome keep loading.
Step 5. look at "Loaded script" of VSCODE , "webpack" "Sourcecode" are not ready.

Verbose logs:
[Error group logs](https://drive.google.com/file/d/1pK4kAuRQn0juqWw2-0U3MXhrdRc0TfEw/view?usp=share_link)

["Non breakpoint "group logs:](https://drive.google.com/file/d/1IwpqUS980_WA5oCA2nKdskaACyhoSSno/view?usp=share_link)

My Launch.json
```
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch chrome webRoot outFiles",
            "url": "http://localhost:3000",

            "webRoot": "${workspaceFolder}/src",

            "sourceMaps": true,
            "trace": true,
            "sourceMapPathOverrides": {
                "webpack:///./src/*": "${webRoot}/src/*",
                "webpack:///src/*": "${webRoot}/src/*"
            },
            "outFiles":[
                "${workspaceFolder}/src/*.js",
                "${workspaceFolder}/src/*.ts",
                "${workspaceFolder}/src/**/*.js",
                "${workspaceFolder}/src/**/*.js",
                "${workspaceFolder}/web_ui/**/*.js",
            ]
            // "sourceMapPathOverrides": "${workspaceFolder}/src/index.js",
        },
```

In Error group logs. 
There is a "runtime.exception" on line:106
`{"tag":"runtime.exception","timestamp":1678851260061,"message":"Unhandled error in debug adapter","metadata":{"message":"Cannot read properties of undefined (reading 'location')","stack":"TypeError: Cannot read properties of undefined (reading 'location')\n\t
at j._onPaused (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:948470)\n\t
at /home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:945783\n\t
at i.fire (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:1012991)\n\t
at t.ListenerMap.emit (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:1013454)\n\t
at c._processResponse (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:993322)\n\t
at c._onMessage (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:993025)\n\t
at t.default._onMessage (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:990936)\n\t
at /home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:989701\n\t
at i.fire (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:1012991)\n\t
at A.<anonymous> (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:995869)\n\t
at A.o (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:725923)\n\t
at A.emit (node:events:526:28)\n\tat e.exports.q (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:762770)\n\t
at e.exports.emit (node:events:526:28)\n\tat e.exports.dataMessage (/home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:740261)\n\t
at /home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:739763\n\t
at /home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:733029\n\t
at /home/gary021/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/extensions/ms-vscode.js-debug/src/extension.js:2:733921\n\t
at afterWrite (node:internal/streams/writable:497:5)\n\t
at onwrite (node:internal/streams/writable:477:7)\n\t
at Zlib.cb (node:internal/streams/transform:202:7)\n\t
at Zlib.processCallback (node:zlib:612:8)"},"level":3}`

before line:107 
`{"tag":"runtime.sourcecreate","timestamp":1678851260062,"message":"Creating source from url","metadata":{"inputUrl":"http://localhost:3000/static/js/bundle.js"},"level":0}`

I believe this is the root of the problem.

I uesd [Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) before. 
It worked very well until I reinstall VSCODE and found it already be deprecated.
Now I only have to use javaScript debugger. 

I have tried 
- [x] Fix launch.json
- [x] Run it on other computer
- [x] Clone codebase a new one
- [x] Clear Setting.json of VSCode
- [x] Install old version "Debugger for Chrome" (but it seems not service now.)
- [x] Reinstall VSCode
- [x] Reinstall chrome

Could you help me ? 🥺🥺🥺

This is my first time report issue. 
I hope it won't be too sloppy.

Thanks

**Comment by waldemar-p** [comment]
> Hi @YiFan0221 - we had the same issue and today (after days of digging into it) we found that the problem was belonging to the Javascript Debug extension. So in order to fix the issue you have to do the following steps:
> 
> 1. In the Extensions search for your Javascript Debugger extension and disable it
> 2. In the Extensions search for @id:ms-vscode.js-debug-nightly and install it (this Javascript Debugger (Nightly))
> 3. A Visual studio code reload is required
> 
> After these steps all worked fine for us. Please let me know how it goes for you.
> 
> The "Nightly" version of Javascript Debugger contains all the most recent changes/fixes that are built at night on daily basis that can be available before that a new version is shipped.

I have the same Issue and sadly after following your instructions it still persists.

**Comment by DarioP66** [comment]
@waldemar-p  - you have to reload the Extensions and make sure the Javascript Debugger is disabled (which means that on it you should see the button to enable it)

**Comment by DarioP66** [comment]
@waldemar-p  - I am glad to hear that 👍 
It seems to me it is only slower the very first time we do load with breakpoints for the first time

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-js-debug/issues/1604

**Comment by YiFan0221** [comment]
It still not work.
Even "yarn start" could not start up service today.

**Comment by DarioP66** [comment]
@YiFan0221 - Did you reload VS Code after the Extension Changes? Make sure that JS Debugger extension is really disabled (which should have the enable button on it)

**Comment by YiFan0221** [comment]
@DarioP66 Sure ,I did.

**Comment by DarioP66** [comment]
@YiFan0221 - Make sure the standard Javascript Debugger is disabled and appears like this:
![image](https://user-images.githubusercontent.com/127953724/225866903-acf0c9a7-7485-4ea2-aa7d-5a0b07ce6d58.png)

**Comment by YiFan0221** [comment]
I said, I had did that. 😂
