### ISSUE TITLE
TypeError: t.lastIndexOf is not a function

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-js-debug#1611]
```
2023-03-17 13:32:32.640 [error] TypeError: t.lastIndexOf is not a function
    at zl (c:\Users\huer\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2023.3.817\src\extension.js:85:11808)
    at pr._addSourceMapSources (c:\Users\huer\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2023.3.817\src\extension.js:101:2046)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at pr._addSource (c:\Users\huer\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2023.3.817\src\extension.js:101:298)
```

**Comment by connor4312** [comment]
How did you reach this bug? Only way I could see this happening is if a sourcemap had invalid non-string data in its sourcemap sourcesContent

**Comment by joyceerhl** [comment]
I don't recall doing anything unusual, was probably debugging either VS Code or Remote Repos. I haven't seen this since, will reopen if I find a repro
