### ISSUE TITLE
Debugger support for node V10

### ISSUE THREAD

**Issue by origeva** [microsoft/vscode-js-debug#1636]
Tested on node v10.16.3
The debugger will throw exception when starting a node application:

root@myserver:~/code/my-project# node .
/root/.vscode-server/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/extensions/ms-vscode.js-debug/src/bootloader.js:8
`+r)),e.removeListener("error",er),e.destroy()}});var Rs=V((Vu,Cs)=>{"use strict";var xa=Object.create,pt=Object.defineProperty,ba=Object.getOwnPropertyDescriptor,Ss=Object.getOwnPropertyNames,va=Object.getPrototypeOf,Sa=Object.prototype.hasOwnProperty,Ea=(e,t)=>function(){return t||(0,e[Ss(e)[0]])((t={exports:{}}).exports,t),t.exports},Ta=(e,t)=>{for(var r in t)pt(e,r,{get:t[r],enumerable:!0})},Es=(e,t,r,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let s of Ss(t))!Sa.call(e,s)&&s!==r&&pt(e,s,{get:()=>t[s],enumerable:!(n=ba(t,s))||n.enumerable});return e},Ca=(e,t,r)=>(r=e!=null?xa(va(e)):{},Es(t||!e||!e.__esModule?pt(r,"default",{value:e,enumerable:!0}):r,e)),Ra=e=>Es(pt({},"__esModule",{value:!0}),e),Aa=Ea({"node_modules/request-light/lib/node/main.js"(e){(()=>{var t={46:(i,a)=>{"use strict";Object.defineProperty(a,"__esModule",{value:!0}),a.default=function(l,f,{signal:c}={}){retu

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:285:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

I tried running the debugger with node v18.14.1 and it was working fine.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1624#issuecomment-1492438222
