### ISSUE TITLE
Can't debug an electron application

### ISSUE THREAD

**Issue by javigaralva** [microsoft/vscode-js-debug#1641]
**Describe the bug**
Can't debug an electron application. In previous VS Code versions I can debug perfectly.

**To Reproduce**
1. Press F5 (or select the launch configuration) to debug.

**Log File**

[vscode-debugadapter-e3cd4656.json.gz](https://github.com/microsoft/vscode-js-debug/files/11157054/vscode-debugadapter-e3cd4656.json.gz)

**VS Code Version:** 
Version: 1.77.0
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:02:16.981Z (6 days ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.77.0 Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36

**Additional context**

This is the `launch.json` file:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Main Process",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}/blz-suite",
            "runtimeExecutable": "${workspaceRoot}/blz-suite/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/blz-suite/node_modules/.bin/electron.cmd"
            },
            "args": [
                "."
            ],
            "runtimeArgs": [
                "--preserve-symlinks"
            ],
            "outputCapture": "std",
            "trace": true
        }
    ]
}
```

And this is the console output:

```sh
Verbose logs are written to:
c:\Users\xxx\AppData\Roaming\Code\logs\20230405T104413\window2\exthost\ms-vscode.js-debug\vscode-debugadapter-e3cd4656.json.gz
C:\xxx\blz/blz-suite/node_modules/.bin/electron.cmd --preserve-symlinks .
runtime.launch Bootloader imported {
  env: {
    inspectorIpc: '\\\\.\\pipe\\node-cdp.28220-90e163db-4.sock',
    deferredMode: false,
    waitForDebugger: '',
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    onlyEntrypoint: false,
    verbose: true,
    autoAttachMode: 'always',
    fileCallback: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\node-debug-callback-514903bb6f8a6488'
  },
  args: [
    'C:\\Program Files\\nodejs\\node.exe',
    'C:\\xxx\\blz\\blz-suite\\node_modules\\electron\\cli.js',
    '--preserve-symlinks',
    '.'
  ]
}
runtime Set debug mode { mode: 0 }
Debugger listening on ws://127.0.0.1:53235/09a913ca-5d0a-4e23-b4a6-7afb5563d9a7
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\bootloader.js:8
`+r)),e.removeListener("error",er),e.destroy()}});var Rs=V((Vu,Cs)=>{"use strict";var xa=Object.create,pt=Object.defineProperty,ba=Object.getOwnPropertyDescriptor,Ss=Object.getOwnPropertyNames,va=Object.getPrototypeOf,Sa=Object.prototype.hasOwnProperty,Ea=(e,t)=>function(){return t||(0,e[Ss(e)[0]])((t={exports:{}}).exports,t),t.exports},Ta=(e,t)=>{for(var r in t)pt(e,r,{get:t[r],enumerable:!0})},Es=(e,t,r,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let s of Ss(t))!Sa.call(e,s)&&s!==r&&pt(e,s,{get:()=>t[s],enumerable:!(n=ba(t,s))||n.enumerable});return e},Ca=(e,t,r)=>(r=e!=null?xa(va(e)):{},Es(t||!e||!e.__esModule?pt(r,"default",{value:e,enumerable:!0}):r,e)),Ra=e=>Es(pt({},"__esModule",{value:!0}),e),Aa=Ea({"node_modules/request-light/lib/node/main.js"(e){(()=>{var t={46:(i,a)=>{"use strict";Object.defineProperty(a,"__esModule",{value:!0}),a.default=function(l,f,{signal:c}={}){return new Promise((d

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:815:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Function.Module._load (internal/modules/cjs/loader.js:648:12)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1044:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:422:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:54:3)
    at internal/bootstrap/environment.js:12:1
Waiting for the debugger to disconnect...
```

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode-js-debug/issues/1624#issuecomment-1492438222
