### ISSUE TITLE
[Bug] RN application crashes from VSCode 1.83.0

### ISSUE THREAD

**Issue by EzioLi01** [microsoft/vscode-js-debug#1837]
Hey @connor4312, we found that react-native application will be crashed when update vscode to 1.83.0, checked this issue is occurring from js-debug v1.83.0 prod and v2023.9.1317 nightly. https://github.com/microsoft/vscode-react-native/issues/2052

Here is the screen record and js-debug trace log, could you please help to check if we have any updates may cause this issue? Thank you!

Repro step:
1. Install react-native by `npm i -g react-native`
2. Create template app by `npx react-native init sampleApp`
3. Install `react-native-tools` in vscode
4. Run `npm run android` to run app in emulator
5. Add `Attach to Hermes application - Experimental` in launch.json with default options
6. Attach debugger, add breakpoint and trigger it

Record:
![AppCrash](https://github.com/microsoft/vscode-js-debug/assets/19662219/c73e6b78-680a-493c-8498-64372c128a8c)

Trace:
[vscode-debugadapter-5f2fdf71.json.gz](https://github.com/microsoft/vscode-js-debug/files/12836906/vscode-debugadapter-5f2fdf71.json.gz)

**Comment by connor4312** [comment]
It seems to crash when this function is called on various objects in the scope, which is used to generate the previews seen in the **Variables** view. I'm guessing this is some kind of native crash; more info about what's going wrong would help. A native crash would not really be an issue in the debugger but we can see if a workaround is available

https://github.com/microsoft/vscode-js-debug/blob/eb545faf20e798ca6abcd9a11cc89af4422b4467/src/adapter/templates/getStringyProps.ts#L25-L76

**Comment by EzioLi01** [comment]
Thanks @connor4312 sharing information, I will try to debug on this. Also adding some log in DevTools console.

```
console.ts:137 [Extension Host] TypeError: Cannot read properties of undefined (reading 'map')
	at c:\Users\v-yukl\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:103:6964
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async mn.getBreakpointLocations (c:\Users\v-yukl\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:103:7197)
	at async c:\Users\v-yukl\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:159:4398
	at async Zl._onMessage (c:\Users\v-yukl\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:71:4859)
$ @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:456
Q @ rpcProtocol.ts:441
M @ rpcProtocol.ts:371
L @ rpcProtocol.ts:297
(anonymous) @ rpcProtocol.ts:161
z @ event.ts:1138
fire @ event.ts:1169
fire @ ipc.net.ts:650
Y.onmessage @ localProcessExtensionHost.ts:581

```


```
ERR Invalid debug adapter: Error: Invalid debug adapter
    at v.m (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1543:95)
    at v.$acceptDAError (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1542:7624)
    at m.S (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:18856)
    at m.Q (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:18622)
    at m.M (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:17715)
    at m.L (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:16794)
    at u.value (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:15597)
    at c.z (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at r.fire (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:14393)
    at Y.onmessage (vscode-file://vscode-app/c:/Users/v-yukl/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1652:1077)
```

**Comment by benjaminbi** [comment]
adding some info
the issue seems occur since by https://github.com/microsoft/vscode-js-debug/commit/676e7e7a9c86b8ce72f10cbdb86df2e1809846a0. The previous commit (https://github.com/microsoft/vscode-js-debug/commit/72c0276263be7a59ada0366341d3d3a6be5ceaa3) works well on my machine.

**Comment by EzioLi01** [comment]
@connor4312, I think this should be the root cause. When we attach debugger to RN application, js-debug will get breakpoint location in function:
> https://github.com/microsoft/vscode-js-debug/blob/eb545faf20e798ca6abcd9a11cc89af4422b4467/src/adapter/breakpoints.ts#L313

In `line 373`:
> https://github.com/microsoft/vscode-js-debug/blob/eb545faf20e798ca6abcd9a11cc89af4422b4467/src/adapter/breakpoints.ts#L370-L397

the function `Debugger.getPossibleBreakpoints` got the empty breakpoint object `r={}`, so the exception will be throwed since `r.locations=undefined` that cannot call function `map`.

But I have checked source url, the breakpoint start and end location should get correctly in 
> https://github.com/microsoft/vscode-js-debug/blob/eb545faf20e798ca6abcd9a11cc89af4422b4467/src/adapter/breakpoints.ts#L321-L332

I'm not familiar with CDP api, @connor4312 could you please guide me on this? Any info you needed please let me know. I will keep on investigating this issue.

**Comment by EzioLi01** [comment]
Thank you @connor4312 for the quick response, I will do some testing on this, any found will comment here!

**Comment by EzioLi01** [comment]
Hey @connor4312, it should be the correct location. In new method `getEnhancedName()`, app will crash on `callFunctionOn`:

> https://github.com/microsoft/vscode-js-debug/blob/2bf84580011121e751e98bf648e28f50edafb3b5/src/adapter/stackTrace.ts#L319-L323 

And I do some testing on my project, seems this crash can be fixed on `react-native-tools` by updating `callFunctionOn` event. I will try on this firstly. Please keep this issue opening, and I will close it if I can fix it on my project. 

Thanks again for your positive help!

**Comment by EzioLi01** [comment]
Close this issue, since it's resolved in RNT project.
