### ISSUE TITLE
Error processing completions: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-js-debug#192]
1. Have a simple `console.log` program
2. Start debugging using node-pwa debugger. Hit a breakpoint, open debug console
3. In the input type something, make it multiline via `shift + enter`. Delete some characters, continue typing -> notice error in the dev tools console

![connor](https://user-images.githubusercontent.com/1926584/71098170-90c55180-21b1-11ea-9e24-d492693cfc81.gif)

```
Error processing completions: TypeError: Cannot read property 'length' of undefined
	at Object.positionToOffset (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:1:22859)
	at Object.completions (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:29:157074)
	at v.completions (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:23:77611)
	at /Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:29:149040
	at h._withThread (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:29:153285)
	at /Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:29:149023
	at u._onMessage (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:15:2339478)
	at u._handleData (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:15:2340931)
	at Socket.<anonymous> (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:15:2337708)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17): Error: Error processing completions: TypeError: Cannot read property 'length' of undefined
	at Object.positionToOffset (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:1:22859)
	at Object.completions (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:29:157074)
	at v.completions (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:23:77611)
	at /Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:29:149040
	at h._withThread (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:29:153285)
	at /Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:29:149023
	at u._onMessage (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:15:2339478)
	at u._handleData (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:15:2340931)
	at Socket.<anonymous> (/Users/isidor/.vscode-oss-dev/extensions/ms-vscode.js-debug-nightly-2019.12.16803/src/extension.js:15:2337708)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
    at RawDebugSession.handleErrorResponse (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/rawDebugSession.js:517:20)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/rawDebugSession.js:495:59
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async DebugSession.completions (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/debugSession.js:445:30)
    at async Object.provideCompletionItems (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/debug/browser/repl.js:63:57)
    at async Promise.all (index 0)
```

**Comment by connor4312** [comment]
In looks like in this scenario VS Code trims the leading newlines whitespace but still indicates to the debug adapter that we're on line 4. Imo the correct behavior here would be either to preserve the leading lines or adjust the `line` to account for the trimmed portion. Thoughts?

![](https://memes.peet.io/img/19-12-f5c35534-6bf8-4b4b-91d3-ad9c9fbe34cb.png)

**Comment by isidorn** [comment]
VSCode should just always pass the whole input text. So now I am doing just that, and the adapter should parse it and only look at the passed line if it wants. Hopefully this does not break any extensions..

**Comment by isidorn** [comment]
Fixed via https://github.com/microsoft/vscode/commit/71eb6ad17eaf49a46fd176ca74a083001e17f7de
