### ISSUE TITLE
While stepping, VS Code debugger periodically disconnects

### ISSUE THREAD

**Issue by johncrim** [microsoft/vscode-js-debug#1947]
**Description**
While stepping through code in VS Code, the debugger periodically detaches - program execution is stopped, but VS Code appears to be running, not on a breakpoint (the pause button is enabled but does nothing, and the play button is not visible). I am attached to Chrome, and if I switch to Chrome dev tools I can see the DevTools debugger stopped on the line that I expected to step to in VS Code. 

If I continue stepping in Chrome I can often get to a point where the active line re-appears in VS Code, and then I can continue stepping in VS Code until this occurs again.

**To Reproduce**
Unfortunately I don't have a repro case, but I do have a consistent stack trace. Each time this happens, I see this error in the Extension Host Output window, which definitely seems related:

```
2024-02-22 16:53:00.619 [warning] TextEditor is closed/disposed
2024-02-22 16:53:15.249 [warning] TextEditor is closed/disposed
2024-02-22 16:53:21.159 [error] TypeError: Cannot read properties of undefined (reading 'includes')
	at t._shouldEnablePerScriptSms (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:115:26487)
	at t._onPaused (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:115:12074)
	at c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:115:9322
	at Y.fire (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:72:27848)
	at nh.emit (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:72:28225)
	at iv._processResponse (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:95:10654)
	at iv._onMessage (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:95:10333)
	at jt._onMessage (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:95:8307)
	at c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:95:7109
	at Y.fire (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:72:27848)
	at t.<anonymous> (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:139:31241)
	at Nv (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:26:53399)
	at t.n (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:26:52687)
	at t.emit (node:events:514:28)
	at DS.Aae (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:26:67389)
	at DS.emit (node:events:514:28)
	at DS.dataMessage (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:26:46076)
	at DS.getData (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:26:45224)
	at DS.startLoop (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:26:41880)
	at DS._write (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:26:41153)
	at writeOrBuffer (node:internal/streams/writable:392:12)
	at _write (node:internal/streams/writable:333:10)
	at DS.write (node:internal/streams/writable:337:10)
	at Socket.qv (c:\Users\redacted\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:26:68095)
	at Socket.emit (node:events:514:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Socket.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

Based on this error, my guess is that `script.url` is `undefined` here:
https://github.com/microsoft/vscode-js-debug/blob/19cd30297dc05b7a7fa9d1d02a8e9dfc1749362e/src/adapter/threads.ts#L1936

**Log File**

Will review and try to provide...

**VS Code Version:**

Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by johncrim** [comment]
Lmk if you want the log - I can email it to you, but from looking at it the Extension Host output above seems a strong indicator. I think it is more useful than the JSON log, from looking at both.

To reiterate, every time I'm stepping and lose context, I get the stack trace above in the Extension Host window.

**Comment by johncrim** [comment]
I can confirm that modifying the `_shouldEnablePerScriptSms()` fn in `C:\Users\my_name\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js` to:

```js
_shouldEnablePerScriptSms(e){return e.data?.url?.includes("@vite/client")?!0:e.reason!=="instrumentation"||!br(e.data?.sourceMapURL)?!1:e.data.url?.startsWith("webpack")||e.data.url?.startsWith("ng:")}
```

By replacing `.url` => `?.url` *fixes this issue*.

**Comment by connor4312** [comment]
Thanks, I thought I already fixed that while looking at another issue, but maybe it didn't get into PR.

**Comment by connor4312** [comment]
This is fixed on https://github.com/microsoft/vscode-js-debug#nightly-extension already!

**Comment by johncrim** [comment]
Can confirm this issue is fixed in the nightly extension. Thanks!!
