### ISSUE TITLE
Error in the js-debug bootloader

### ISSUE THREAD

**Issue by Kniaziev** [microsoft/vscode-js-debug#2071]
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at new NodeError (node:internal/errors:371:5)
    at Object.inspectorOpen [as open] (node:inspector:168:11)
    at /private/var/folders/65/3df7955x7v3dgmy7fqnngnrw0000gn/T/AppTranslocation/157CE6D3-C836-43E5-ADE3-436CB0929B33/d/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:86060
    at /private/var/folders/65/3df7955x7v3dgmy7fqnngnrw0000gn/T/AppTranslocation/157CE6D3-C836-43E5-ADE3-436CB0929B33/d/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:86087
    at Object.<anonymous> (/private/var/folders/65/3df7955x7v3dgmy7fqnngnrw0000gn/T/AppTranslocation/157CE6D3-C836-43E5-ADE3-436CB0929B33/d/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:86383)
    at n (/private/var/folders/65/3df7955x7v3dgmy7fqnngnrw0000gn/T/AppTranslocation/157CE6D3-C836-43E5-ADE3-436CB0929B33/d/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:110)
    at /private/var/folders/65/3df7955x7v3dgmy7fqnngnrw0000gn/T/AppTranslocation/157CE6D3-C836-43E5-ADE3-436CB0929B33/d/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:902
    at Object.<anonymous> (/private/var/folders/65/3df7955x7v3dgmy7fqnngnrw0000gn/T/AppTranslocation/157CE6D3-C836-43E5-ADE3-436CB0929B33/d/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:912)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by gabriel-mauricioo** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by connor4312** [comment]
Are you running with coverage? This was a bug in Node.js: https://github.com/nodejs/node/issues/46110
