### ISSUE TITLE
"Cannot read property 'token' of undefined" on killing a proccess

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#209]
I had VS Code running and stopped it through the call stack explorer, it died correctly but I got this error message. Nothing in the console.

![image](https://user-images.githubusercontent.com/8586769/71842350-46c7e100-3076-11ea-824d-e263045f86da.png)

**Comment by JacksonKearl** [comment]
Tried to repro and didn't get that model, but got this notification instead?

![image](https://user-images.githubusercontent.com/8586769/71842439-7d9df700-3076-11ea-9f22-6462455f6e9e.png)

**Comment by JacksonKearl** [comment]
Also getting it when restarting a process

**Comment by connor4312** [comment]
```
TypeError: Cannot read property 'token' of undefined
    at DebugService.createSession (file:///Users/copeet/Github/vscode/out/vs/workbench/contrib/debug/browser/debugService.js:297:227)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async DebugService.startDebugging (file:///Users/copeet/Github/vscode/out/vs/workbench/contrib/debug/browser/debugService.js:253:32)
```

From [here](https://github.com/microsoft/vscode/blob/81fb34c445098d43d0f25b4e1868ca421022d4de/src/vs/workbench/contrib/debug/browser/debugService.ts#L389)
