### ISSUE TITLE
Cannot mix BigInt and other types, use explicit conversions

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#258]
I had the debugger die again on me today and this is what I saw in the devtools console: (and there are LOTS of these entries)

![image](https://user-images.githubusercontent.com/641685/73101858-9e5fac80-3ebe-11ea-8511-84996e5ec217.png)

```
[Extension Host] rejected promise not handled within 1 second: TypeError: Cannot mix BigInt and other types, use explicit conversions (at c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:42)
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot mix BigInt and other types, use explicit conversions	at t.default._onMessage (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2513322)	at w.<anonymous> (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2523361)	at w.r (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:21:225181)	at w.emit (events.js:203:13)	at e.exports.R (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2531775)	at e.exports.emit (events.js:203:13)	at e.exports.dataMessage (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2537783)	at e.exports.getData (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2537025)	at e.exports.startLoop (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2534434)	at e.exports._write (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2533816)	at doWrite (_stream_writable.js:418:12)	at writeOrBuffer (_stream_writable.js:402:5)	at e.exports.Writable.write (_stream_writable.js:302:11)	at Socket.z (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2532300)	at Socket.emit (events.js:203:13)	at addChunk (_stream_readable.js:295:12)	at readableAddChunk (_stream_readable.js:276:11)	at Socket.Readable.push (_stream_readable.js:210:10)	at TCP.onStreamRead (internal/stream_base_commons.js:166:17) (at c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:121)
t.log @ console.ts:137
mainThreadExtensionService.ts:65 [[object Object]]Cannot mix BigInt and other types, use explicit conversions
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
mainThreadExtensionService.ts:66 TypeError: Cannot mix BigInt and other types, use explicit conversions
	at t.default._onMessage (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2513322)
	at w.<anonymous> (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2523361)
	at w.r (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:21:225181)
	at w.emit (events.js:203:13)
	at e.exports.R (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2531775)
	at e.exports.emit (events.js:203:13)
	at e.exports.dataMessage (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2537783)
	at e.exports.getData (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2537025)
	at e.exports.startLoop (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2534434)
	at e.exports._write (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2533816)
	at doWrite (_stream_writable.js:418:12)
	at writeOrBuffer (_stream_writable.js:402:5)
	at e.exports.Writable.write (_stream_writable.js:302:11)
	at Socket.z (c:\Users\Eric\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.33183\src\extension.js:15:2532300)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
```

**Comment by johnemau** [comment]
I ran into this as well and I have a code fix, I will put up a PR tomorrow.

**Comment by connor4312** [comment]
Cool. Please let me know if you run into issues with the PR, I'd like to get this fixed today :)

**Comment by rebornix** [comment]
@connor4312 could you please provide detailed steps about how to test?

**Comment by connor4312** [comment]
sorry, I've already verified this fix, didn't realize js-debug would be included in endgame :)
