### ISSUE TITLE
Sometimes starting a debug session launches, but never shows the debug toolbar

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#265]
Here are the logs for the last time it happened:
[vscode-debugadapter.zip](https://github.com/microsoft/vscode-js-debug/files/4118938/vscode-debugadapter.zip)

Once this issue starts, it seems that I need to restart vscode in order for it to work properly again.

Here is an error I see in the devtools console that may or may not be related.

```
ERR [createInstance] ie depends on UNKNOWN service privateReplService.: Error: [createInstance] ie depends on UNKNOWN service privateReplService.
    at h._createInstance (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1578:41)
    at h.createInstance (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1577:754)
    at e.get selectReplAction (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5130:769)
    at e.s.<computed> (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:51:384)
    at e.getActions (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5130:632)
    at e.setActions (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5021:297)
    at e.updateActions (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5021:633)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5126:215
    at c.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:116:893)
    at j.doCreateSession (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5559:24)
    at j.createSession (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5558:394)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async j.startDebugging (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5556:846)
log.ts:197   ERR TreeError [CallStackView] Data tree node not found: [object Object]: Error: TreeError [CallStackView] Data tree node not found: [object Object]
    at q.getDataNode (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1086:503)
    at q.expand (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1084:710)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5499:135
    at Set.forEach (<anonymous>)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5499:114
log.ts:197   ERR [createInstance] ie depends on UNKNOWN service privateReplService.: Error: [createInstance] ie depends on UNKNOWN service privateReplService.
    at h._createInstance (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1578:41)
    at h.createInstance (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1577:754)
    at e.get selectReplAction (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5130:769)
    at e.s.<computed> (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:51:384)
    at e.getActions (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5130:632)
    at e.setActions (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5021:297)
    at e.updateActions (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5021:633)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5126:215
    at c.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:116:893)
    at j.doCreateSession (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5559:24)
    at j.createSession (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5558:394)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async j.startDebugging (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5556:846)
```

**Comment by connor4312** [comment]
I've seen this as well, occasionally. @isidorn is that REPL error suspicious to you? Or any other high level ideas before I spend time diving in and trying to figure out a repro+fix 🙂

**Comment by eamodio** [comment]
FYI, this happens pretty often for me while debugging vscode using the `Debug VS Code Main, Renderer & Extension Host` launch config. Sometimes it will happen after a few iterations of start debugging, close the vscode debuggee window (which stops the session). Or usually quicker if I click the restart debugging to restart the debugging session

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/88990
I know how to fix and will fix later today / tomorrow. No need to investigate further.
Appolgies for the breakage.
