### ISSUE TITLE
Error parsing mappings (code 4): invalid base 64 character while parsing a VLQ

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#483]
We got a lot of unhandled rejections in VS with that message. If we can't parse the sourcemap, there is a possibility that we won't be able to bind some breakpoints. It'd be great if we could print some message in the console, or similar, and also set the status of any unbound breakpoint to say: "This might be caused because source-map aaa.js.map couldn't be parsed because...."

These are the stack traces that we got:
[
  Error: Error parsing mappings (code 4): invalid base 64 character while parsing a VLQ
    at l._parseMappings (source-map-consumer.js:360:13)
    at l._getMappingsPtr (source-map-consumer.js:315:12)
    at f (source-map-consumer.js:510:14)
    at Object.withMappingCallback (wasm.js:95:11)
    at l.originalPositionFor (source-map-consumer.js:508:16)
    at t.SourceMap.originalPositionFor (sourceMap.js:61:30)
    at O.getOptiminalOriginalPosition (sources.js:491:31)
    at O._sourceMappedUiLocation (sources.js:448:28)
    at O.preferredUiLocation (sources.js:394:39)",
  "Error: Error parsing mappings (code 4): invalid base 64 character while parsing a VLQ
    at l._parseMappings (source-map-consumer.js:360:13)
    at l._getMappingsPtr (source-map-consumer.js:315:12)
    at f (source-map-consumer.js:510:14)
    at Object.withMappingCallback (wasm.js:95:11)
    at l.originalPositionFor (source-map-consumer.js:508:16)
    at t.SourceMap.originalPositionFor (sourceMap.js:61:30)
    at O.getOptiminalOriginalPosition (sources.js:491:31)
    at O._sourceMappedUiLocation (sources.js:448:28)
    at O.uiLocation [as preferredUiLocation] (sources.js:394:39)
    at k._onConsoleMessage (threads.js:777:17)",
  "Error: Error parsing mappings (code 4): invalid base 64 character while parsing a VLQ
    at l._parseMappings (source-map-consumer.js:360:13)
    at l._getMappingsPtr (source-map-consumer.js:315:12)
    at f (source-map-consumer.js:510:14)
    at Object.withMappingCallback (wasm.js:95:11)
    at l.originalPositionFor (source-map-consumer.js:508:16)
    at t.SourceMap.originalPositionFor (sourceMap.js:61:30)
    at O.getOptiminalOriginalPosition (sources.js:491:31)
    at O._sourceMappedUiLocation (sources.js:448:28)
    at O.preferredUiLocation (sources.js:394:39)
    at runNextTicks (internaltask_queues.js:58:5)",
  "Error: Error parsing mappings (code 4): invalid base 64 character while parsing a VLQ
    at l._parseMappings (source-map-consumer.js:360:13)
    at l._getMappingsPtr (source-map-consumer.js:315:12)
    at f (source-map-consumer.js:510:14)
    at Object.withMappingCallback (wasm.js:95:11)
    at l.originalPositionFor (source-map-consumer.js:508:16)
    at t.SourceMap.originalPositionFor (sourceMap.js:61:30)
    at O.getOptiminalOriginalPosition (sources.js:491:31)
    at O._sourceMappedUiLocation (sources.js:448:28)
    at O.uiLocation [as preferredUiLocation] (sources.js:394:39)
    at a (smartStepping.js:9:11)"
]

**Comment by digeff** [comment]
@connor4312 We got some telemetry that some stackTrace requests are also failing with this error:
Error: Error parsing mappings (code 4): invalid base 64 character while parsing a VLQ
    at l._parseMappings (source-map-consumer.js:360:13)
    at l._getMappingsPtr (source-map-consumer.js:315:12)
    at f (source-map-consumer.js:510:14)
    at Object.withMappingCallback (wasm.js:95:11)
    at l.originalPositionFor (source-map-consumer.js:508:16)
    at t.SourceMap.originalPositionFor (sourceMap.js:61:30)
    at O.getOptiminalOriginalPosition (sources.js:491:31)
    at O._sourceMappedUiLocation (sources.js:448:28)
    at O.preferredUiLocation (sources.js:394:39)

**Comment by connor4312** [comment]
![](https://memes.peet.io/img/20-06-b1e3d00e-8818-42b4-8a71-f7b47b3e09fe.png)

**Comment by digeff** [comment]
Awesome :)
