### ISSUE TITLE
can't find runtimExecutable path on OSX catalina

### ISSUE THREAD

**Issue by justinwhall** [microsoft/vscode-js-debug#510]
This _was_ working for me. Unsure if the upgrade to catalina broke it or what.

When launching I get the following errors in the VSCODE log.  This my issue was the same as [this one](https://github.com/microsoft/vscode-js-debug/issues/212) but alas, the solution in that issue did not work for me. 

```
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump | grep -i 'google chrome\( canary\)\?.app$'
```
returns nothing. 

Also setting the runtimeExecutable to the following does nothing.
```
"runtimeExecutable": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
```
That returns the following when launching :
```
[2020-06-04 20:59:21.466] [renderer2] [error] spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT: Error: spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[2020-06-04 20:59:21.500] [renderer2] [error] No debug adapter, can not send 'exception breakpoints': Error: No debug adapter, can not send 'exception breakpoints'
    at e.sendExceptionBreakpoints (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6440:934)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6472:390
    at Y (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6477:9)
    at e.sendExceptionBreakpoints (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6472:208)
    at e.sendAllBreakpoints (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6471:484)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6447:39
```

Setting it to stable returns the following when launching:
```
[2020-06-04 20:52:51.438] [renderer2] [error] spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT: Error: spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by connor4312** [comment]
Where do you have Chrome installed on your machine?

**Comment by justinwhall** [comment]
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
```
Worth noting, VSCODE does not want the escaped spaces.

**Comment by connor4312** [comment]
I'm rather confused -- that path is where Chrome is, but Node gets ENOENT when trying to spawn it. The lack of registration in launch services also suggests something is going wrong. I suggest try to delete and re-install Chrome on your machine and see if that fixes it.
