### ISSUE TITLE
VSCode JS debugging error on MAC Insiders build

### ISSUE THREAD

**Issue by scottmchargue** [microsoft/vscode-js-debug#545]
Error: Cannot find module '/var/folders/l0/wf24khkn4z15f_xmbqb7rb8m0000gn/T/vscode-js-debug-bootloader.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Prior suggestions to toggle autoattach on and off, etc have not helped.

**Comment by connor4312** [comment]
The key is to toggle auto attach to disabled, and then enabled again. Additionally, if you're using `js-debug-nightly`, make sure that the built-in "stable" version is disabled. Please confirm whether that works for you or not. Thanks!
