### ISSUE TITLE
[ERR_INSPECTOR_ALREADY_ACTIVATED] Error when start debugging

### ISSUE THREAD

**Issue by Hacksign** [microsoft/vscode-js-debug#552]
I've got a "error" when I start a debug, the error content is below:

```javascript
/usr/bin/npm run-script dev
Debugger listening on ws://127.0.0.1:39153/123f7339-8c62-4d1d-a850-def0c3f0813d
For help, see: https://nodejs.org/en/docs/inspector
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at Object.inspectorOpen [as open] (inspector.js:137:11)
    at /usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:86060
    at /usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:86087
    at Object.<anonymous> (/usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:86383)
    at n (/usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:110)
    at /usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:902
    at Object.<anonymous> (/usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
Debugger attached.
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at Object.inspectorOpen [as open] (inspector.js:137:11)
    at /usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:86060
    at /usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:86087
    at Object.<anonymous> (/usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:86383)
    at n (/usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:110)
    at /usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:902
    at Object.<anonymous> (/usr/lib/code/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
```

and the `dev` part in `package.json` is:

```javascript
{
  ......
  "scripts": {
    "build": "npm run build:server; npm run build:client; npm run build:assets",
    "build:server": "webpack --config build/webpack.config.server.ts",
    "build:client": "webpack --config build/webpack.config.client.ts",
    "build:assets": "cp-cli build/assets/ dist/assets",
    "dev": "cross-env NODE_ENV=development node --trace-warnings --inspect=127.0.0.1:9229 --require=ts-node/register ./src/index.ts",
    "start": "cross-env NODE_ENV=production node ./dist/server/server.js",
    "package": "npm run build && tar jcvf dist.tar.bz2 dist/ package.json"
  },
  ......
}
```

vscode version info:
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-19T17:35:52.982Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.6-arch1-1
```

**Comment by connor4312** [comment]
Are you using Node 14?

**Comment by connor4312** [comment]
To verify:

- Use the very latest Node 14 version
- Try to debug any Node script through any method.

**Comment by Hacksign** [comment]
> Are you using Node 14?

Yeap, Node 14.5.0

This situation is reproduced by create a test js file:

![img](https://i.ibb.co/SBhkvX2/20200703132612.png)
