### ISSUE TITLE
Error in the js-debug bootloader

### ISSUE THREAD

**Issue by beci** [microsoft/vscode-js-debug#556]
The following error occured during debugging a typescript app:

```
Debugger attached.
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at Object.inspectorOpen [as open] (inspector.js:137:11)
    at /opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:84007
    at /opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:84034
    at Object.<anonymous> (/opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:84330)
    at n (/opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:110)
    at /opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:902
    at Object.<anonymous> (/opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
/opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js:1
Could not read source map for file:///home/xxx/src/yyy/node_modules/typescript/lib/typescript.js: ENOENT: no such file or directory, open '/home/xxx/src/yyy/node_modules/typescript/lib/typescript.js.map'
```
Launch config related part:
```json
    {
      "type": "node",
      "request": "launch",
      "name": "scrape ts",
      "cwd": "${workspaceFolder}",
      "args": ["--last", "10"], 
      "runtimeArgs": ["-r", "ts-node/register"],
			"protocol": "inspector",
			"internalConsoleOptions": "openOnSessionStart",
    }
```

The debugging working despite the mentioned error message.

**Comment by connor4312** [comment]
Thanks, duplicates https://github.com/microsoft/vscode-js-debug/issues/552 and is fixed in yesterday's nightly/build 1.47.2.
