### ISSUE TITLE
Exception has occurred: Error: Module did not self-register.

### ISSUE THREAD

**Issue by MarcilioCortes** [microsoft/vscode-js-debug#567]
Open on debug mode (-- inspect) after instal 1.47.0 VS Code version today

at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (c:\MCApps\plat01\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

**Comment by connor4312** [comment]
That stack trace is coming from sqlite in your own dependencies. Googling the issue, that seems to be related to native modules not being built on the correct native node API. Did you update Node at the same time as you installed VS Code?
