### ISSUE TITLE
Can't debug via Google Chrome extension after upgrade to 1.47.1

### ISSUE THREAD

**Issue by kashamalasha** [microsoft/vscode-js-debug#616]
**Describe the bug**
After upgrade to 1.47.1 I can't start debug using Google Chrome.

**To Reproduce**
1. Go to Run tab
2. Click on Launch index.html
3. Wait until Google Chrome is opened

**Log File**
```
Error processing launch: Error: Could not attach to main target
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:33166
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processTimers (internal/timers.js:472:9)
	at async f.prepareLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2619729)
	at async f.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2620329)
	at async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25637)
	at async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25208)
	at async Promise.all (index 6)
	at async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:24468)
	at async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2459238)
```

**Launch.json file**
```
{
  "version": "0.1.0",
  "configurations": [
      {
          "name": "Launch index.html",
          "type": "chrome",
          "request": "launch",
          "file": "${workspaceFolder}/index.html",
          "webRoot": "${workspaceFolder}",
          "trace": true
      }
  ]
}
```

**VS Code Version:** 
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Additional context**
Trace file is attached.
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4924924/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
Thanks for the issue and log, see here for the fix: https://github.com/microsoft/vscode/issues/102529#issuecomment-658453060

**Comment by kashamalasha** [comment]
Thanks. It works.
