### ISSUE TITLE
'Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated' with config 'Node.js: Launch Program'

### ISSUE THREAD

**Issue by MattyAB** [microsoft/vscode-js-debug#675]
I am running Node.js v14.7.0 and VSCode 1.46.1, and also tried with Node.js v12.18.3 (LTS) with the same issue arising. Using windows 10 on a surface laptop 3.

I am running a very simple webserver: 

`const http = require('http');

http.createServer(function(req, res) {
  res.writeHead(200, {'Content-Type' : 'text/plain'});
  res.end('Hello, world!');
}).listen(8080);`

And get the following issue:

`C:\Program Files\nodejs\node.exe [MYUSERDIR]\OneDrive\Code\Node.js\app.js
Debugger listening on [DEBUGURL]
For help, see: https://nodejs.org/en/docs/inspector
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at Object.inspectorOpen [as open] (inspector.js:137:11)
    at [MYUSERDIR]\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\bootloader.bundle.js:1:86060
    at [MYUSERDIR]\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\bootloader.bundle.js:1:86087
    at Object.<anonymous> ([MYUSERDIR]\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\bootloader.bundle.js:1:86383)
    at n ([MYUSERDIR]\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\bootloader.bundle.js:1:110)
    at [MYUSERDIR]\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\bootloader.bundle.js:1:902
    at Object.<anonymous> ([MYUSERDIR]\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\bootloader.bundle.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module '[MYUSERDIR]\OneDrive\Code\Node.js\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Process exited with code 1`

**Comment by connor4312** [comment]
Please update your VS Code version; this is fixed in 1.47.2.
