### ISSUE TITLE
升级后报错

### ISSUE THREAD

**Issue by gbbyuluo** [microsoft/vscode-js-debug#680]
yuluogedeMacBook-Air:de-components yuluoge$ npm -v
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/var/folders/qr/3ck99gp52d38yfntk2f8s4300000gn/T/vscode-js-debug-bootloader.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:812:12)
    at preloadModules (internal/bootstrap/node.js:599:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by connor4312** [comment]
Please see here: https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467
