### ISSUE TITLE
Crashes right after start with spawn sh ENOENT

### ISSUE THREAD

**Issue by simonknittel** [microsoft/vscode-js-debug#802]
**Describe the bug**
The debugger crashes immediately after I run it because of "spawn sh ENOENT"

**To Reproduce**

**Terminal output**
```
(base) simon.knittel@c1579 xxx %  cd /Users/simon.knittel/Documents/xxx/xxx/repos/xxx ; /usr/bin/env PATH=/Users/simon.knittel/.nvm/versions/node/v12.19.0/bin 'NODE_OPTIONS=--require "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/var/folders/ps/59j65g7x4ps192gmp0b88kqcv4n64r/T/node-cdp.11857-5.sock","deferredMode":false,"waitForDebugger":"","execPath":"/Users/simon.knittel/.nvm/versions/node/v14.6.0/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/var/folders/ps/59j65g7x4ps192gmp0b88kqcv4n64r/T/node-debug-callback-a7dd8f262f6f0176"}' /Users/simon.knittel/.nvm/versions/node/v12.19.0/bin/npm run-script start 
Debugger attached.

> xxx@1.32.2 start /Users/simon.knittel/Documents/xxx/xxx/repos/xxx
> gulp watch

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn sh
npm ERR! file sh
npm ERR! path sh
npm ERR! errno ENOENT
npm ERR! xxx@1.32.2 start: `gulp watch`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the xxx@1.32.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simon.knittel/.npm/_logs/2020-10-14T06_53_02_762Z-debug.log
Waiting for the debugger to disconnect...
```

**launch.json**
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "npm start",
      "request": "launch",
      "runtimeArgs": [
        "run-script",
        "start"
      ],
      "runtimeExecutable": "npm",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "pwa-node",
      "runtimeVersion": "12.19.0",
      "trace": true,
      "console": "integratedTerminal"
    }
  ]
}
```

**package.json**
```
...
"scripts": {
  "start": "gulp watch"
}
....
```

**npm log file**
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/simon.knittel/.nvm/versions/node/v12.19.0/bin/node',
1 verbose cli   '/Users/simon.knittel/.nvm/versions/node/v12.19.0/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle xxx@1.32.2~prestart: xxx@1.32.2
6 info lifecycle xxx@1.32.2~start: xxx@1.32.2
7 verbose lifecycle xxx@1.32.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle xxx@1.32.2~start: PATH: /Users/simon.knittel/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/simon.knittel/Documents/xxx/xxx/repos/xxx/node_modules/.bin:/Users/simon.knittel/.nvm/versions/node/v12.19.0/bin
9 verbose lifecycle xxx@1.32.2~start: CWD: /Users/simon.knittel/Documents/xxx/xxx/repos/xxx
10 silly lifecycle xxx@1.32.2~start: Args: [ '-c', 'gulp watch' ]
11 info lifecycle xxx@1.32.2~start: Failed to exec start script
12 silly lifecycle xxx@1.32.2~start: Returned: code: -2  signal: null
13 info lifecycle xxx@1.32.2~start: Failed to exec start script
14 verbose stack Error: xxx@1.32.2 start: `gulp watch`
14 verbose stack spawn sh ENOENT
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
14 verbose stack     at onErrorNT (internal/child_process.js:469:16)
14 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
15 verbose pkgid xxx@1.32.2
16 verbose cwd /Users/simon.knittel/Documents/xxx/xxx/repos/xxx
17 verbose Darwin 19.6.0
18 verbose argv "/Users/simon.knittel/.nvm/versions/node/v12.19.0/bin/node" "/Users/simon.knittel/.nvm/versions/node/v12.19.0/bin/npm" "run-script" "start"
19 verbose node v12.19.0
20 verbose npm  v6.14.8
21 error code ELIFECYCLE
22 error syscall spawn sh
23 error file sh
24 error path sh
25 error errno ENOENT
26 error xxx@1.32.2 start: `gulp watch`
26 error spawn sh ENOENT
27 error Failed at the xxx@1.32.2 start script.
27 error This is probably not a problem with npm. There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

**Log File**
Too large to upload it anywhere ... Any suggestions?

**VS Code Version:** 1.50.0

**Additional context**
Tried with different Node.js versions.

**Comment by connor4312** [comment]
Does this work if you `npm run start` from the command line / terminal?
